<?php

require_once '../db_connect.php';


//Generate Activation String
function generateRandomString() {
    $characters = '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ';
    $randomString = '';
    for ($i = 0; $i < 5; $i++) {
        $index = rand(0, strlen($characters) - 1);
        $randomString .= $characters[$index];
    }
    return $randomString;
}




$name = "Test";
$email = $_POST["email"];
$subject = "Activation OTP";
$activationCode = generateRandomString();


$message = "<html>
<body>
    <h2>Hello Winner &#128512;</h2>
    <h3>Blazingly Fast &#9889;</h3>
    <p style='font-size: 15px;'>
        Your AutoGenerated OTP Code Is <br> &#128073; 
        <code style='color: #AA77FF;font-family: Google Sans; font-weight: 600; font-size: 20px;'>" . $activationCode . "</code>
    </p></body>
</html>";


require "vendor/autoload.php";

use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\SMTP;

$mail = new PHPMailer(true);

// $mail->SMTPDebug = SMTP::DEBUG_SERVER;

$mail->isSMTP();
$mail->SMTPAuth = true;
$mail->isHTML(true);

$mail->Host = "smtp.gmail.com";
$mail->SMTPSecure = PHPMailer::ENCRYPTION_STARTTLS;
$mail->Port = 587;

$mail->Username = "cashout.earn@gmail.com";
$mail->Password = "bblpdzkwvlgidwud";

$mail->setFrom("cashout.earn@gmail.com", "Cashout Kenya");
$mail->addAddress($email, $name);

$mail->Subject = $subject;
$mail->Body = $message;

$mail->send();

echo "$activationCode";